SRCS = \
src/utils/token.c \
src/utils/ast/and_or.c \
src/utils/ast/command.c \
src/utils/ast/redir.c \
src/utils/ast/redir_loop.c \
src/utils/ast/cmd_loop.c \
src/utils/free_ast_2.c \
src/utils/ft_strndup.c \
src/utils/ms_string.c \
src/utils/free_ast_1.c \
src/utils/free_and_null.c \
src/utils/check_token_type.c \
src/utils/write_error.c \
src/syntax_processor/ast_builder/ast_builder.c \
src/syntax_processor/ast_builder/build_ast_from_tokens.c \
src/syntax_processor/ast_builder/create_cmd_list.c \
src/syntax_processor/ast_builder/create_redir_list.c \
src/syntax_processor/ast_builder/processes.c \
src/syntax_processor/tokenizer/process_special_char.c \
src/syntax_processor/tokenizer/processes.c \
src/syntax_processor/tokenizer/tokenizer.c \
src/syntax_processor/str_to_ast.c \
src/syntax_processor/check_syntax/check_syntax.c \
src/executor/command/builtin/cd.c \
src/executor/command/builtin/echo.c \
src/executor/command/builtin/env.c \
src/executor/command/builtin/cd.c \
src/executor/command/builtin/exit.c \
src/executor/command/builtin/export.c \
src/executor/command/builtin/unset.c \
src/executor/command/exec_external_cmd.c \
src/executor/pipeline/wait_pids.c \
src/executor/pipeline/exec_pipeline.c \
src/executor/pipeline/exec_cmd_list.c \
src/executor/exec_ast.c \
src/expander/expander.c \
src/expander/redir/generate_filename.c \
src/expander/redir/redir_quote_removal_handler.c \
src/expander/redir/generate_heredoc_file_handler.c \
src/expander/redir/redir_split_handler.c \
src/expander/redir/input_heredoc_content_handler.c \
src/expander/redir/redir_expand_handler.c \
src/expander/command/expand/handler.c \
src/expander/command/quote_remove/quote_remove.c \
src/expander/command/word_split/word_split.c \
src/expander/command/word_split/split_token.c \
src/expander/command/to_char/generate_argv.c \
src/expander/common/utils.c \
src/expander/common/quote_remove_core.c \
src/expander/common/expand_single_token.c \
src/expander/common/expand_variable.c \
src/expander/common/process_expansion_core.c \
src/minishell.c \
