SRCS = \
src/utils/token.c \
src/utils/ast/and_or.c \
src/utils/ast/command.c \
src/utils/ast/redir.c \
src/utils/free_ast_2.c \
src/utils/ft_strndup.c \
src/utils/ms_string.c \
src/utils/free_ast_1.c \
src/syntax_processor/ast_builder/ast_builder.c \
src/syntax_processor/ast_builder/build_ast_from_tokens.c \
src/syntax_processor/ast_builder/create_cmd_list.c \
src/syntax_processor/ast_builder/create_redir_list.c \
src/syntax_processor/ast_builder/processes.c \
src/syntax_processor/tokenizer/process_special_char.c \
src/syntax_processor/tokenizer/processes.c \
src/syntax_processor/tokenizer/utils.c \
src/syntax_processor/tokenizer/tokenizer.c \
src/syntax_processor/str_to_ast.c \
src/executor/command/process_redir_list.c \
src/executor/command/builtin/exec_builtin_cmd.c \
src/executor/command/builtin/pwd.c \
src/executor/command/builtin/echo.c \
src/executor/command/builtin/env.c \
src/executor/command/builtin/cd.c \
src/executor/command/builtin/exit.c \
src/executor/command/builtin/export.c \
src/executor/command/builtin/unset.c \
src/executor/command/exec_external_cmd.c \
src/executor/pipeline/wait_pids.c \
src/executor/pipeline/exec_pipeline.c \
src/executor/pipeline/exec_cmd_list.c \
src/executor/exec_ast.c \
src/expander/expander.c \
src/expander/utils.c \
src/expander/word_split/word_split.c \
src/expander/word_split/split_token.c \
src/expander/expand/expand_single_token.c \
src/expander/expand/expand_variable.c \
src/expander/expand/process_expansion_core.c \
src/expander/quote_remove/quote_remove.c \
src/expander/to_char/generate_argv.c \
src/minishell.c \
